### PR TITLE
Target

### PR DESCRIPTION
**Pull request by jonathan-benn**
Removed 'target' dirty hack

Fixes note35/sinon#36

### CODE REVIEW

**Comment by note35** [comment]
Hi jonathan,

Many thanks for your effort.
But again, due to github's limitation, please pulling from current master to resolve the conflict!

Regards,
--kir

**Comment by jonathan-benn** [comment]
Hi Kir,

You're welcome. I have rebased and this seems to have fixed the merge conflicts.

--Jonathan

**Review by note35 — APPROVED** [review]
LGTM. 
Since the implementation wasn't changed, I am still not sure this solution is perfect or not.

**Comment by jonathan-benn** [comment]
Hi Kir,

> Since the implementation wasn't changed, I am still not sure this solution is perfect or not.

I think that fundamentally your solution was a good one. My modification just makes your solution _official_, and I think it also improves the results of `stub.onCall(i).args` by permanently removing the unnecessary `self` parameter.

Unfortunately, code often has weird edge cases like this one. It's normal.

--Jonathan

**Pull request merged**
